### PR TITLE
Added lastMessage function to examples

### PR DESCRIPTION
**Pull request by markzakharyan**
(Tested, it works :D)

Changed old cloud functions example to js and a newer (not deprecated environment). Also added cloud functions example for changing a room's `lastMessage`

### CODE REVIEW

**Comment by SalahAdDin** [comment]
It looks cool, but the **Room** model has no a `lastMessage` field.

**Comment by demchenkoalex** [comment]
It will have soon, and it will be an array

**Comment by markzakharyan** [comment]
> It looks cool, but the **Room** model has no a `lastMessage` field.

I wrote a firebase function making it

**Comment by SalahAdDin** [comment]
> > It looks cool, but the **Room** model has no a `lastMessage` field.
> 
> This creates it if it doesn't exist already

i was talking about the `dart` model.

**Comment by markzakharyan** [comment]
> > > It looks cool, but the **Room** model has no a `lastMessage` field.
> > 
> > This creates it if it doesn't exist already
> 
> i was talking about the `dart` model.

Check out the issue I made, it contains some nice code that gets latest message without using the dart model. I'm using this in the meantime until it gets added to the package.

**Comment by SalahAdDin** [comment]
Is it ready to be merged?

**Comment by mashegoindustries** [comment]
Hi,

I think we may need to change the onWrite to onUpdate

This will ensure that rooms document will only get updated just once.

At the moment it updates twice, since the other cloud function (changeMessageStatus) will trigger another onWrite

So I simply changed from onWrite to onUpdate

exports.changeLastMessage = functions.firestore
  .document("rooms/{roomId}/messages/{messageId}")
  .**onUpdate**((change, context) => {
    const message = change.after.data();
    if (message) {
      return db.doc("rooms/" + context.params.roomId).update({
        lastMessage: message,
      });
    } else {
      return null;
    }
  });

**Comment by demchenkoalex** [comment]
Hi @markzakharyan sorry was on vacation, but now I'm back. If you can please test @mashegoindustries suggestion and update the PR if needed that would be great! I have also updated Dart model (it now has `List<Message> lastMessages` inside the `room` class) can you please use this array? (you can just put one value inside like this `[message]`). It is an array because in our future SaaS solution we will populate it with 10 or 20 latest messages, so when you enter the room you have not one, but complete first page of messages loaded.

**Comment by markzakharyan** [comment]
> Hi,
> 
> I think we may need to change the onWrite to onUpdate
> 
> This will ensure that rooms document will only get updated just once.
> 
> At the moment it updates twice, since the other cloud function (changeMessageStatus) will trigger another onWrite
> 
> So I simply changed from onWrite to onUpdate
> 
> exports.changeLastMessage = functions.firestore
> .document("rooms/{roomId}/messages/{messageId}")
> .**onUpdate**((change, context) => {
> const message = change.after.data();
> if (message) {
> return db.doc("rooms/" + context.params.roomId).update({
> lastMessage: message,
> });
> } else {
> return null;
> }
> });

I just tested it, it works well. But maybe it would be better to have just one function maybe `onMessageSend` or something rather than multiple smaller functions? It just feels more elegant to have one function running on the Firestore update than two. What do you think?@demchenkoalex @mashegoindustries

**Comment by demchenkoalex** [comment]
I guess that's fine if everything still works :)

**Comment by SalahAdDin** [comment]
@markzakharyan Could you also add a example function for the `updateAt` feature?

**Comment by markzakharyan** [comment]
> @markzakharyan Could you also add a example function for the `updateAt` feature?

I'm sorry @SalahAdDin what feature are you referring to?

**Comment by SalahAdDin** [comment]
> > @markzakharyan Could you also add a example function for the `updateAt` feature?
> 
> I'm sorry @SalahAdDin what feature are you referring to?

@markzakharyan This one: https://github.com/flyerhq/flutter_firebase_chat_core/blob/main/lib/src/firebase_chat_core.dart#L179

**Comment by demchenkoalex** [comment]
Can I merge this? Can't find an update to a single function. Request above is not related to this PR.

**Comment by markzakharyan** [comment]
> Can I merge this? Can't find an update to a single function. Request above is not related to this PR.

Go ahead

**Comment by demchenkoalex** [comment]
Thanks for the PR!

**Comment by demchenkoalex** [comment]
Updated `lastMessage: message` to `lastMessages: [message]` in this commit https://github.com/flyerhq/flutter_firebase_chat_core/commit/12d47b91e19166865217a837144610402f22e160 so there is access to `lastMessages` in Flutter because this is what we have in types. Hopefully doesn't break anything :)

**Pull request merged**
